export const SelectOptionData = [
    { moduleName: 'Status', value: ['Active', 'Completed', 'Suspended'] },
    { moduleName: 'Service', value: ['RPM'] },
    { moduleName: 'Provider', value: ['Hot Provider', 'Cold Provider'] },
    { moduleName: 'PPO', value: ['PPO', 'HMO'] },
    { moduleName: 'CareTeam', value: ['Hot CareTeam', 'Cold CareTeam'] },
    { moduleName: 'InputField', value: ['dob', 'id', 'phone'] },
    {
        moduleName: 'TimeLog',
        value: ['Apr, 2024', 'Mar, 2024', 'Feb, 2024', 'Jan, 2024', 'Dec, 2023', 'Nov, 2023'],
    },
    {
        moduleName: 'PeriodSelect',
        value: ['Today', '1W', '1M'],
    },
    { moduleName: 'Facility', value: ['Facility'] },
    { moduleName: 'RoomNo', value: ['RoomNo'] },
    { moduleName: 'Branch', value: ['Branch'] },
    { moduleName: 'Suffix', value: ['Suffix'] },
    { moduleName: 'Gender', value: ['Gender'] },
    { moduleName: 'PrimaryLanguage', value: ['PrimaryLanguage'] },
    { moduleName: 'DXcode', value: ['DXcode'] },
    { moduleName: 'PrimaryPhysician', value: ['PrimaryPhysician'] },
    { moduleName: 'PhoneType', value: ['PhoneType'] },
    { moduleName: 'state', value: ['state'] },
];
